#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U

#define JOYSTICK_AXIS_COUNT 2
#define JOYSTICK_BUTTON_COUNT 2

#define JOYSTICK_X_PIN GP26
#define JOYSTICK_Y_PIN GP27
#define JOYSTICK_SW_PIN GP16

#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP0
#define I2C1_SCL_PIN GP1

// Ignore tiny movements around center.
#define JOYSTICK_DEADZONE 24

#define OLED_DISPLAY_ADDRESS 0x3C
#define OLED_DISPLAY_64X32
#define OLED_BRIGHTNESS 120
